export const unihanFieldInfo = [
  ['kAccountingNumeric', 1],
  ['kAlternateTotalStrokes', 2],
  ['kBigFive', 3],
  ['kCCCII', 4],
  ['kCNS1986', 5],
  ['kCNS1992', 6],
  ['kCangjie', 7],
  ['kCantonese', 8],
  ['kCheungBauer', 9],
  ['kCheungBauerIndex', 10],
  ['kCihaiT', 11],
  ['kCompatibilityVariant', 12],
  ['kCowles', 13],
  ['kDaeJaweon', 14],
  ['kEACC', 16],
  ['kFenn', 17],
  ['kFennIndex', 18],
  ['kFourCornerCode', 19],
  ['kFrequency', 20],
  ['kGB0', 21],
  ['kGB1', 22],
  ['kGB3', 23],
  ['kGB5', 24],
  ['kGB7', 25],
  ['kGB8', 26],
  ['kGSR', 27],
  ['kGradeLevel', 28],
  ['kHDZRadBreak', 29],
  ['kHKGlyph', 30],
  ['kHKSCS', 31],
  ['kHanYu', 32],
  ['kHangul', 33],
  ['kHanyuPinlu', 34],
  ['kHanyuPinyin', 35],
  ['kIBMJapan', 36],
  ['kIICore', 37],
  ['kIRGDaeJaweon', 38],
  ['kIRGDaiKanwaZiten', 39],
  ['kIRGHanyuDaZidian', 40],
  ['kIRGKangXi', 41],
  ['kIRG_GSource', 42],
  ['kIRG_HSource', 43],
  ['kIRG_JSource', 44],
  ['kIRG_KPSource', 45],
  ['kIRG_KSource', 46],
  ['kIRG_MSource', 47],
  ['kIRG_TSource', 48],
  ['kIRG_USource', 49],
  ['kIRG_VSource', 50],
  ['kJIS0213', 51],
  ['kJapaneseKun', 52],
  ['kJapaneseOn', 53],
  ['kJis0', 54],
  ['kJis1', 55],
  ['kKPS0', 56],
  ['kKPS1', 57],
  ['kKSC0', 58],
  ['kKSC1', 59],
  ['kKangXi', 60],
  ['kKarlgren', 61],
  ['kKorean', 62],
  ['kLau', 63],
  ['kMainlandTelegraph', 64],
  ['kMandarin', 65],
  ['kMatthews', 66],
  ['kMeyerWempe', 67],
  ['kMorohashi', 68],
  ['kNelson', 69],
  ['kOtherNumeric', 70],
  ['kPhonetic', 71],
  ['kPrimaryNumeric', 72],
  ['kPseudoGB1', 73],
  ['kRSAdobe_Japan1_6', 74],
  ['kRSJapanese', 75],
  ['kRSKanWa', 76],
  ['kRSKangXi', 77],
  ['kRSKorean', 78],
  ['kRSUnicode', 79],
  ['kSBGY', 80],
  ['kSemanticVariant', 81],
  ['kSimplifiedVariant', 82],
  ['kSpecializedSemanticVariant', 83],
  ['kTaiwanTelegraph', 84],
  ['kTang', 85],
  ['kTotalStrokes', 86],
  ['kTraditionalVariant', 87],
  ['kVietnamese', 88],
  ['kXHC1983', 89],
  ['kXerox', 90],
  ['kZVariant', 91],
  ['kUnihanCore2020', 92],
  ['kIRG_UKSource', 93],
  ['kIRG_SSource', 94],
  ['kTGH', 95],
  ['kKoreanName', 96],
  ['kJa', 97],
  ['kJoyoKanji', 98],
  ['kKoreanEducationHanja', 99],
  ['kJinmeiyoKanji', 100],
  ['kTGHZ2013', 101],
  ['kSpoofingVariant', 102],
  ['kStrange', 103],
  ['kSMSZD2003Index', 104],
  ['kMojiJoho', 105],
  ['kVietnameseNumeric', 106],
  ['kZhuangNumeric', 107],
  ['kTayNumeric', 108],
  ['kJapanese', 109],
  ['kFanqie', 110],
  ['kSMSZD2003Readings', 111],
  ['kZhuang', 112],
  ['kJapaneseOldVariant', 113],
  ['kJapaneseNewVariant', 114]
];

export const unicodeFieldInfo = [
  'General_Category',
  'Canonical_Combining_Class',
  'Bidi_Class',

  // We broke it up into two parts for easier viewing
  // 'Decomposition_Type_and_Mapping',
  'decompositionMapping',
  'decompositionType',

  // We broke this up for more convenient querying/display
  /*
  'Decimal',
  'Digit',
  'Numeric',
   */
  'numericType',
  'numericValue',

  'Bidi_Mirrored',
  'Unicode_1_Name',
  'ISO_Comment',
  'Simple_Uppercase_Mapping',
  'Simple_Lowercase_Mapping',
  'Simple_Titlecase_Mapping'
];
