// As the Unicode server does not have CORS enabled, we can't adapt
//  this file for the browser, but we're keeping this file for demonstrating
//  an approach for live-obtaining the live version.
//  The current process we're using on our (bahai-browser.org) server
//  was instead just to use
//  `curl -LO https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip`
//  while in the `bahai-browser.org/download/unihan` directory and serve
//  `Unihan.zip` with a static file server so our browser script (elsewhere)
//  can download it and unpack its contents to supply to the method shared with
//  this file, `parseUnihanFromTextFileStrings.js`. (CORS is not currently
//  enabled, however, so this would need to be adjusted for cross-origin
//  browser use.)

import fs from 'node:fs/promises';

import download from 'download';

// eslint-disable-next-line no-shadow -- Clearer
import fetch from 'file-fetch';

import parseUnihanFromTextFileStrings from
  '../browser_action/unicode/parseUnihanFromTextFileStrings.js';

const args = process.argv.slice(2);

const targetDir = `${process.cwd()}/download/unihan`;
const targetJSONUnihan = `${targetDir}/unihan.json`;
const targetUnihanFields =
  `${process.cwd()}/browser_action/unicode/unihanFields.js`;
if (args.includes('download')) {
  await download(
    'https://www.unicode.org/Public/UCD/latest/ucd/Unihan.zip', targetDir, {extract: true}
  );
  // eslint-disable-next-line no-console -- CLI
  console.log('Completed download and extraction portion');
}

await addScript(targetDir);

/**
 * Formats string values as single-quoted, comma-separated JS array
 *   entries wrapped at ~78 characters, matching this project's lint style.
 * @param {string[]} values
 * @returns {string}
 */
function formatQuotedArrayLines (values) {
  const lines = [];
  let line = '  ';
  values.forEach((value, idx) => {
    const piece = `'${value}'${idx === values.length - 1 ? '' : ', '}`;
    if (line.length > 2 && line.length + piece.length > 78) {
      lines.push(line.trimEnd());
      line = '  ';
    }
    line += piece;
  });
  lines.push(line.trimEnd());
  return lines.join('\n');
}

/**
 * @param {string} baseURL
 * @returns {Promise<void>}
 */
async function addScript (baseURL) {
  const scriptFileAsStrings = await Promise.all([
    'Unihan_DictionaryIndices.txt',
    'Unihan_DictionaryLikeData.txt',
    'Unihan_IRGSources.txt',
    'Unihan_NumericValues.txt',
    'Unihan_OtherMappings.txt',
    'Unihan_RadicalStrokeCounts.txt',
    'Unihan_Readings.txt',
    'Unihan_Variants.txt'
  ].map(async (file) => {
    const fileObj = await fetch(`${baseURL}/${file}`);
    return await fileObj.text();
  }));

  const {rows, fields} = parseUnihanFromTextFileStrings(scriptFileAsStrings);

  await fs.writeFile(targetJSONUnihan, JSON.stringify(rows));

  // Drop the leading `code_pt` entry: `unicodecharref.js`'s `Unihan`
  //   display array only lists the actual Unihan fields, correlating
  //   positionally with each row's data (which is likewise stored without
  //   its own leading code point; see `UnihanDatabase.upgradeneeded`).
  const unihanFields = fields.slice(1);
  await fs.writeFile(
    targetUnihanFields,
    '// Auto-generated by `tools/unihan-import.js`; do not edit by hand.\n' +
    '// Must stay in the exact column order used to build\n' +
    '//   `download/unihan/unihan.json` (see\n' +
    '//   `parseUnihanFromTextFileStrings.js`), since `unicodecharref.js`\n' +
    "//   reads values by this array's position.\n" +
    `const unihanFields = [\n${formatQuotedArrayLines(unihanFields)}\n];\n\n` +
    'export default unihanFields;\n'
  );

  // eslint-disable-next-line no-console -- CLI
  console.log('Wrote file');
}
